/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './*.js',
    './pages/*.js',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error-container': '#ffdad6',
        'surface-container-lowest': '#0d0f0c',
        'surface-bright': '#383a36',
        'on-secondary-fixed': '#271900',
        'on-tertiary': '#293139',
        'on-tertiary-container': '#222b32',
        'on-primary-container': '#481d00',
        'secondary-container': '#feb700',
        'error': '#ffb4ab',
        'primary-fixed-dim': '#ffb68d',
        'surface-dim': '#121411',
        'outline': '#a58c7f',
        'on-primary-fixed': '#321200',
        'on-background': '#e3e3de',
        'tertiary-fixed-dim': '#bec7d1',
        'tertiary-container': '#89929b',
        'inverse-surface': '#e3e3de',
        'surface-tint': '#ffb68d',
        'on-primary': '#532200',
        'secondary': '#ffdb9d',
        'on-secondary-container': '#6b4b00',
        'secondary-fixed': '#ffdea8',
        'surface-variant': '#333532',
        'surface-container': '#1e201d',
        'on-primary-fixed-variant': '#763400',
        'primary': '#ffb68d',
        'on-tertiary-fixed-variant': '#3f4850',
        'surface': '#121411',
        'on-error': '#690005',
        'inverse-on-surface': '#2f312e',
        'primary-fixed': '#ffdbc9',
        'surface-container-low': '#1a1c19',
        'on-secondary-fixed-variant': '#5e4200',
        'surface-container-highest': '#333532',
        'inverse-primary': '#9a4600',
        'error-container': '#93000a',
        'outline-variant': '#564338',
        'tertiary': '#bec7d1',
        'secondary-fixed-dim': '#ffba20',
        'on-surface-variant': '#ddc1b3',
        'surface-container-high': '#292a27',
        'on-surface': '#e3e3de',
        'background': '#121411',
        'primary-container': '#df7328',
        'on-tertiary-fixed': '#141d24',
        'on-secondary': '#412d00',
        'tertiary-fixed': '#dae3ee',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        '5xl': '2.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '32px',
        'section-gap': '120px',
        'container-padding-desktop': '64px',
        'container-padding-mobile': '24px',
        unit: '8px',
      },
      fontFamily: {
        'headline': ['Sora', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '48px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      animation: {
        'morph': 'morph 20s ease-in-out infinite',
        'dash': 'dash 20s linear infinite',
      },
      keyframes: {
        morph: {
          '0%': { borderRadius: '42% 58% 70% 30% / 45% 45% 55% 55%' },
          '50%': { borderRadius: '70% 30% 46% 54% / 30% 29% 71% 70%' },
          '100%': { borderRadius: '42% 58% 70% 30% / 45% 45% 55% 55%' },
        },
        dash: {
          to: { strokeDashoffset: '-100' },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
